### ISSUE TITLE
Using with other kalman package - simdkalman

### ISSUE THREAD

**Issue by andrewczgithub** [cvxgrp/auto_ks#1]
Hi @sbarratt !

I love this work!

I was just wondering if I could use the parameter estimation with a different kalman filter package like the one below. Just for speed purposes. 
How would I then structure the model.

Many thanks,
Best,
Andrew

https://github.com/oseiskar/simdkalman

**Comment by sbarratt** [comment]
This will not work directly with that package. However, the math in our
paper can definitely be translated to the formulation used in that package.

**Comment by andrewczgithub** [comment]
Hi @sbarratt !! I have made some progress.
However i get an error with the below-

import simdkalman

kf = simdkalman.KalmanFilter(A, C, np.linalg.inv(W_neg_sqrt @ W_neg_sqrt), np.linalg.inv(V_neg_sqrt @ V_neg_sqrt))
kf = kf.em(measurements, n_iter=10)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-cf8c68f29d06> in <module>
      2 
      3 kf = simdkalman.KalmanFilter(A, C, np.linalg.inv(W_neg_sqrt @ W_neg_sqrt), np.linalg.inv(V_neg_sqrt @ V_neg_sqrt))
----> 4 kf = kf.em(measurements, n_iter=10)

~/env/lib/python3.7/site-packages/simdkalman/kalmanfilter.py in em(self, data, n_iter, initial_value, initial_covariance, verbose)
    732             gains = True,
    733             log_likelihood = False,
--> 734             verbose = verbose)
    735 
    736         if verbose:

~/env/lib/python3.7/site-packages/simdkalman/kalmanfilter.py in compute(self, data, n_test, initial_value, initial_covariance, smoothed, filtered, states, covariances, observations, likelihoods, gains, log_likelihood, verbose)
    526                 print('filtering %d/%d' % (j+1, n_measurements))
    527 
--> 528             y = data[:,j,...].reshape((n_vars, n_obs, 1))
    529 
    530             tup = self.update(m, P, y, log_likelihood)

ValueError: cannot reshape array of size 119 into shape (119,48,1)
This is with your human migration example. 

I was wondering if you could assist 

MAny thanks and kind regards,
Andrew

**Comment by sbarratt** [comment]
According to the documentation (
https://simdkalman.readthedocs.io/en/latest/#simdkalman.KalmanFilter),
the order of arguments are:

```python
simdkalman.KalmanFilter(state_transition, process_noise, observation_model,
observation_noise)
```

So, for you, this would be:
```python
kf = simdkalman.KalmanFilter(A, np.linalg.inv(W_neg_sqrt @ W_neg_sqrt), C,
np.linalg.inv(V_neg_sqrt @ V_neg_sqrt))
```

**Comment by andrewczgithub** [comment]
hi @sbarratt !! thank you so much for your help!!
I tried your code
kf = simdkalman.KalmanFilter(A, np.linalg.inv(W_neg_sqrt @ W_neg_sqrt), C,np.linalg.inv(V_neg_sqrt @ V_neg_sqrt))
kf = kf.em(measurements, n_iter=10)

but still received the error -

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-169f40770e77> in <module>
     68 measurements[~(K & ~M_test)] = np.ma.masked
     69 kf = simdkalman.KalmanFilter(A, np.linalg.inv(W_neg_sqrt @ W_neg_sqrt), C,np.linalg.inv(V_neg_sqrt @ V_neg_sqrt))
---> 70 kf = kf.em(measurements, n_iter=10)
     71 filtered_state_means, _ = kf.smooth(measurements)
     72 yhat_em = filtered_state_means @ C.T

~/tutorial-env/lib/python3.7/site-packages/simdkalman/kalmanfilter.py in em(self, data, n_iter, initial_value, initial_covariance, verbose)
    732             gains = True,
    733             log_likelihood = False,
--> 734             verbose = verbose)
    735 
    736         if verbose:

~/tutorial-env/lib/python3.7/site-packages/simdkalman/kalmanfilter.py in compute(self, data, n_test, initial_value, initial_covariance, smoothed, filtered, states, covariances, observations, likelihoods, gains, log_likelihood, verbose)
    526                 print('filtering %d/%d' % (j+1, n_measurements))
    527 
--> 528             y = data[:,j,...].reshape((n_vars, n_obs, 1))
    529 
    530             tup = self.update(m, P, y, log_likelihood)

ValueError: cannot reshape array of size 119 into shape (119,48,1)


Kind regards,
Andrew

**Comment by sbarratt** [comment]
What’s the shape of measurements

**Comment by andrewczgithub** [comment]
Hi @sbarratt !!
When i do 

measurements.shape

I get -

(119, 48)

**Comment by sbarratt** [comment]
I’m not sure then. You might want to file an issue on the simdkalman
repository. I’m closing this issue.

**Comment by andrewczgithub** [comment]
cheers @sbarratt ! appreciate your help 
Best,
Andrew
