### ISSUE TITLE
Kalman Filter - A Simple 1d time series

### ISSUE THREAD

**Issue by andrewczgithub** [cvxgrp/auto_ks#2]
Hi @sbarratt 
Hope your well.
I am trying to use your software on a simple 1 time series -

array([184.69, 182.92, 182.89, 182.36, 183.48, 183.52, 183.64, 184.14,
       181.69, 183.67, 184.66, 184.42, 183.64, 184.18, 184.3 , 182.79,
       178.89, 178.01, 179.07, 177.35, 179.23, 178.18, 174.17, 175.39,
       175.17, 177.48, 179.68, 180.01, 181.98, 182.07, 183.01, 184.02,
       184.24, 183.02, 184.1 , 183.89, 184.91, 184.84, 184.85, 185.82,
       186.29, 184.98, 187.58, 187.75, 188.18, 188.26, 188.16, 187.23,

I am trying to use your examples as a template and this is what I came up with -

K_gps=y

# initialize parameters
eye = np.eye(3)
zeros = np.zeros((3, 3))
h = 1. / 100.0
lam = 1e-10
alpha = 1e-4
n = 9
m = 8
A = np.bmat([
    [eye, h * eye, zeros],
    [zeros, eye, h * eye],
    [zeros, zeros, eye]
])
C = np.bmat([
    [eye, zeros, zeros],
    [zeros, zeros, eye],
    [np.zeros((2, 3)), np.eye(2), np.zeros((2, 4))]
])
W_neg_sqrt = np.eye(n)
V_neg_sqrt = .01*np.eye(m)
params_initial = auto_ks.KalmanSmootherParameters(np.array(A), np.array(W_neg_sqrt), np.array(C), np.array(V_neg_sqrt))

# proximal operator for r
def prox(params, t):
    r = 0.0
    W_neg_sqrt = params.W_neg_sqrt / (t * alpha + 1.0)
    idx = np.arange(W_neg_sqrt.shape[0])
    W_neg_sqrt[idx, idx] = 0.0
    r += alpha * np.sum(np.square(W_neg_sqrt))
    W_neg_sqrt[idx, idx] = np.diag(params.W_neg_sqrt)

    V_neg_sqrt = params.V_neg_sqrt / (t * alpha + 1.0)
    idx = np.arange(V_neg_sqrt.shape[0])
    V_neg_sqrt[idx, idx] = 0.0
    r += alpha * np.sum(np.square(V_neg_sqrt))
    V_neg_sqrt[idx, idx] = np.diag(params.V_neg_sqrt)

    return auto_ks.KalmanSmootherParameters(A, W_neg_sqrt, C, V_neg_sqrt), r

# choose missing measurements
gps_meas_idx = np.where(K_gps)[0]
np.random.shuffle(gps_meas_idx)
M = np.zeros(y.shape, dtype=np.bool)
M[int(gps_meas_idx.size * .2)] = True

# choose test measurements
M_test = np.zeros(y.shape, dtype=np.bool)
M_test[int(gps_meas_idx.size * .2):int(gps_meas_idx.size * .4)] = True

# evaluate initial parameters
xhat_initial, yhat_initial, DT = auto_ks.kalman_smoother(params_initial, y, K & ~M_test, lam)
loss_auto = np.linalg.norm(yhat_initial[M_test] - y[M_test])**2 / M_test.sum()
print("initial test loss", loss_auto)

# run kalman smoother auto-tuning
tic = time.time()
params, info = auto_ks.tune(params_initial, prox, y, K & ~M_test, M, lam, lr=1e-2, verbose=True, niter=25)
toc = time.time()
print("time", toc-tic, "s")
xhat, yhat, DT = auto_ks.kalman_smoother(params, y, K & ~M_test, lam)

# evaluate
loss_auto = np.linalg.norm(yhat[M_test] - y[M_test])**2 / M_test.sum()
print ("final_test_loss:", loss_auto)

print(np.diag(np.linalg.inv(params.W_neg_sqrt @ params.W_neg_sqrt.T)))
print(np.diag(np.linalg.inv(params.V_neg_sqrt @ params.V_neg_sqrt.T)))

However I am getting the error-

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-83-d2122dd0576c> in <module>
     51 
     52 # evaluate initial parameters
---> 53 xhat_initial, yhat_initial, DT = auto_ks.kalman_smoother(params_initial, y, K & ~M_test, lam)
     54 loss_auto = np.linalg.norm(yhat_initial[M_test] - y[M_test])**2 / M_test.sum()
     55 print("initial test loss", loss_auto)

ValueError: operands could not be broadcast together with shapes (837,2) (838,) 

I was wondering if you could assist. I know if this is a bit of a hack, so if there is an easier way please advise.

Many thanks for your help.
Kind regards,
Andrew

**Comment by sbarratt** [comment]
Andrew, I just added some more shape checks in the code. Can you try the code again and attach a minimum working example script?

**Comment by andrewczgithub** [comment]
Hi @sbarratt !
Thank you so much for your help.
You are very generaous with your time.

The below is honestly the best I could come up with on a 1d uni variate attempt.

```python
from scipy.constants import g
from scipy.spatial.transform import Rotation as R
import navpy
import auto_ks
from pykalman import KalmanFilter
import IPython as ipy
from random import shuffle
from itertools import cycle
from utils import latexify
import time

np.random.seed(0)
from pandas_datareader import data as pdr

import yfinance as yf
yf.pdr_override() # <== that's all it takes :-)

# download dataframe
data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2019-04-30")


df=data

columns = df.columns[1:]
y = np.array(df)
# construct initial parameters
T, n = y.shape
m = n
lam = 1e-10
A = np.array([[1,1],[0,1]])
W_neg_sqrt = np.diag([0.1, 0.01])
C = np.array([[1,0]])
V_neg_sqrt = 1.0
params = auto_ks.KalmanSmootherParameters(A, W_neg_sqrt, C, V_neg_sqrt)

K = np.zeros(y.shape, dtype=bool)
M = np.zeros(y.shape, dtype=bool)
M_test = np.zeros(y.shape, dtype=bool)
for t in range(T):
    idx = np.arange(n)
    np.random.shuffle(idx)
    indices = idx[:30]
    K[t, indices] = True
    np.random.shuffle(indices)
    M[t, indices[:12]] = True
    M_test[t, indices[12:12+5]] = True

    
def prox(params, t):
    return auto_ks.KalmanSmootherParameters(
            np.maximum(params.A),
            W_neg_sqrt,
            C,
            np.diag(np.maximum(params.V_neg_sqrt), 0)
    ), 0.0
    

params_initial = auto_ks.KalmanSmootherParameters(A, W_neg_sqrt, C, V_neg_sqrt)
params, info = auto_ks.tune(params, prox, y, K & ~M_test, lam, M=M, lr=1e-4, verbose=True, niter=50)
```

**Comment by sbarratt** [comment]
This code should work:

```python
import numpy as np
import auto_ks
from pandas_datareader import data as pdr

import yfinance as yf
yf.pdr_override()  # <== that's all it takes :-)

# download dataframe
data = pdr.get_data_yahoo("SPY", start="2000-01-01", end="2019-01-01")

np.random.seed(0)

y = data["Open"][:, None]

T, p = y.shape
n = 2
lam = 1e-6
A = np.array([[1., 1], [0, 1]])
W_neg_sqrt = np.diag([.1, .1])
C = np.array([[1., 0]])
V_neg_sqrt = np.array([[.1]])

K = np.zeros(T * p, dtype=bool)
M = np.zeros(T * p, dtype=bool)
M_test = np.zeros(T * p, dtype=bool)
idx = np.arange(T * p)
np.random.shuffle(idx)
K[idx[:int(T * p * .5)]] = True
M[idx[int(T * p * .5):int(T * p * .75)]] = True
M_test[idx[int(T * p * .75):]] = True

K = K.reshape(T, p)
M = M.reshape(T, p)
M_test = M_test.reshape(T, p)


def prox(params, t):
    return auto_ks.KalmanSmootherParameters(
        A,
        params.W_neg_sqrt,
        C,
        params.V_neg_sqrt
    ), 0.0

params_initial = auto_ks.KalmanSmootherParameters(A, W_neg_sqrt, C, V_neg_sqrt)

xhat, yhat, _ = auto_ks.kalman_smoother(params_initial, y, K | M, lam)
print("initial test cost:", np.sum(np.square((yhat - y)[M_test])))

params, info = auto_ks.tune(
    params_initial, prox, y, K & ~M_test, lam, M=M, lr=1e-1, verbose=True, niter=20)

xhat, yhat, _ = auto_ks.kalman_smoother(params, y, K | M, lam)
print("final test cost:", np.sum(np.square((yhat - y)[M_test])))

print(np.linalg.inv(params.W_neg_sqrt @ params.W_neg_sqrt.T))
print(np.linalg.inv(params.V_neg_sqrt @ params.V_neg_sqrt.T))
```

I get the output:
```bash
initial test cost: 2361.2490162926433
001 | 2.6632e+00 | 1.0000e-01
002 | 2.5395e+00 | 1.5000e-01
003 | 2.2532e+00 | 2.8125e-02
004 | 2.1717e+00 | 6.5918e-04
005 | 2.1684e+00 | 6.1798e-05
006 | 2.1602e+00 | 2.3174e-05
007 | 2.1600e+00 | 3.4761e-05
008 | 2.1537e+00 | 2.6071e-05
009 | 2.1486e+00 | 1.2221e-06
010 | 2.1465e+00 | 4.5828e-07
011 | 2.1464e+00 | 1.7186e-07
012 | 2.1463e+00 | 2.5778e-07
013 | 2.1462e+00 | 9.6669e-08
014 | 2.1462e+00 | 1.4500e-07
015 | 2.1462e+00 | 2.1750e-07
016 | 2.1462e+00 | 1.6313e-07
017 | 2.1462e+00 | 1.2235e-07
018 | 2.1462e+00 | 1.8352e-07
019 | 2.1462e+00 | 1.3764e-07
020 | 2.1462e+00 | 2.0646e-07
final test cost: 2237.5542108324903
[[ 1.21460009e+08 -2.81300870e+07]
 [-2.81300870e+07  6.51495575e+06]]
[[65.35261909]]
```

**Comment by andrewczgithub** [comment]
@sbarratt !! you are a legend!! thanks so much!! it works!!! what a champion!!

I have put together the mean filter and plotting scripts. The fit does look very good, could you possibly just sense check it to make sure I am not doing something erroneous.

If everything is correct this issue can now be closed with compliments.

 ```python

measurements = np.ma.masked_array(y)
measurements[~(K & ~M_test)] = np.ma.masked
kf = KalmanFilter(transition_matrices = A, observation_matrices = C, transition_covariance = np.linalg.inv(W_neg_sqrt @ W_neg_sqrt), observation_covariance = np.linalg.inv(V_neg_sqrt @ V_neg_sqrt))
kf = kf.em(measurements, n_iter=10)
filtered_state_means, _ = kf.smooth(measurements)
yhat_em = filtered_state_means @ C.T
loss_em = np.linalg.norm(yhat_em[M_test] - y[M_test])**2 / M_test.sum()
print("loss_em:", loss_em)

plt.plot(yhat, '-', c='black', label="CA")
plt.plot( y, '-', alpha=.8, c='blue')

plt.legend()
plt.xlabel("year")
plt.ylabel("price")
plt.subplots_adjust(left=.15, bottom=.20)

```
